// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkmfRn7_GZwUslawEuWRYUvkceL96xNg',
    appId: '1:121993344266:web:5ba79677f952793351f6f3',
    messagingSenderId: '121993344266',
    projectId: 'examinantt-ae432',
    authDomain: 'examinantt-ae432.firebaseapp.com',
    storageBucket: 'examinantt-ae432.firebasestorage.app',
    measurementId: 'G-2KK00MFTLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvBJvswL2gDxAsVfzoClrUx5SviCXSK7M',
    appId: '1:121993344266:android:27ebcee3efe000a251f6f3',
    messagingSenderId: '121993344266',
    projectId: 'examinantt-ae432',
    storageBucket: 'examinantt-ae432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHgUcEIxRKuFLE9_5ErYahBYECVFuTC14',
    appId: '1:121993344266:ios:8a30743811dc0d2451f6f3',
    messagingSenderId: '121993344266',
    projectId: 'examinantt-ae432',
    storageBucket: 'examinantt-ae432.firebasestorage.app',
    iosClientId:
        '121993344266-loplaaph95a86a6rcungk7pvqvrbc6ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.examinanttApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHgUcEIxRKuFLE9_5ErYahBYECVFuTC14',
    appId: '1:121993344266:ios:8a30743811dc0d2451f6f3',
    messagingSenderId: '121993344266',
    projectId: 'examinantt-ae432',
    storageBucket: 'examinantt-ae432.firebasestorage.app',
    iosClientId:
        '121993344266-loplaaph95a86a6rcungk7pvqvrbc6ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.examinanttApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADTT_z99DYKO44fHDFV2NSI93Kq4cDVi4',
    appId: '1:121993344266:web:8872ebeffbc4975a51f6f3',
    messagingSenderId: '121993344266',
    projectId: 'examinantt-ae432',
    authDomain: 'examinantt-ae432.firebaseapp.com',
    storageBucket: 'examinantt-ae432.firebasestorage.app',
    measurementId: 'G-YH06JE1K61',
  );
}
